### ISSUE TITLE
1.9 vanilla server not working.

### ISSUE THREAD

**Issue by GaryZ88310** [FlorianMichael/ViaFabricPlus#67] opened 2023-04-23 23:11 UTC
### General Information

ViaFabric Plus, Baritone API, Fabric API. (also had Meteor Client but I yeeted it to see if it was the cause, it was not)

### Bug Description

Joining a friend's vanilla server causes the game to error.
Error:`Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/32 (class 2672) was larger than I expected, found 153600 bytes extra whist reading packet 32`

Works on 1.9.2, so it's purely a 1.9 issue.

### Steps to Reproduce

Join a server thats running 1.9.
That error will appear.

### Expected Behavior

Game should work.

**Comment by Poopooracoocoo** [comment] 2023-04-24 03:52
using baritone by itself isn't alarming but it is with hacks like meteor client. don't expect support

**Comment by allinkdev** [comment] 2023-04-24 07:39
Does the same issue also occur with the Baritone API disabled?

**Comment by allinkdev** [comment] 2023-04-24 09:03
Able to reproduce with only the last version of ViaFabricPlus & Fabric API, on the [official 1.9 dedicated server](https://launcher.mojang.com/v1/objects/b4d449cf2918e0f3bd8aa18954b916a4d1880f0d/server.jar).

**Comment by allinkdev** [comment] 2023-04-24 09:14
> Able to reproduce with only the last version of ViaFabricPlus & Fabric API, on the [official 1.9 dedicated server](https://launcher.mojang.com/v1/objects/b4d449cf2918e0f3bd8aa18954b916a4d1880f0d/server.jar).

Seems to be caused by "ChunkDataS2CPacket".
![2023-04-24_10 13 31](https://user-images.githubusercontent.com/44676012/233953152-b2104a2e-0ef2-4657-afba-4f734573c9f0.png)

**Comment by allinkdev** [comment] 2023-04-24 09:31
Seems like there's something irky going on with ViaBackwards' 1.9 translation, even on the serverside (1.19.4 Paper, latest build), without ViaFabricPlus involved.

![image](https://user-images.githubusercontent.com/44676012/233957273-0b42183d-c8fd-44f4-955f-0b56d4205fa1.png)
![image](https://user-images.githubusercontent.com/44676012/233957293-ea7df632-f8de-4d98-abfe-515df75aff69.png)

**Comment by FlorianMichael** [comment] 2023-04-24 14:56
@Poopooracoocoo It's alright, i don't care which mods you have installed, I will fix issues even tough it's a meteor client incompatibility

**Comment by FlorianMichael** [comment] 2023-04-24 15:15
Hello! This issue is not related to ViaFabricPlus, it's a ViaVersion issue which is now reported, I will close this issue as soon as ViaVersion is fixed

**Closed** 2023-04-24 18:33 UTC
Labels: bug
