### ISSUE TITLE
[Bug]Game freezing when refreshing servers

### ISSUE THREAD

**Issue by x-yingcan-x** [FlorianMichael/ViaFabricPlus#90] opened 2023-05-07 11:47 UTC
### General Information

Minecraft 1.19.4
Fabric API 0.80.0
viafabricplus 2.7.0

### Bug Description

Game freezes when refreshing servers.
[latest.log](https://github.com/FlorianMichael/ViaFabricPlus/files/11414851/latest.log)

### Steps to Reproduce

1. Install those mods
2. Launch game and add some server which needs a long time to ping.
3. Refresh server list
4. Game freezing

### Expected Behavior

Refresh with no freezing

**Comment by x-yingcan-x** [comment] 2023-05-07 13:02
No,only happens when both installed

**Comment by FlorianMichael** [comment] 2023-05-07 13:23
I can't reproduce this and I don't think this is a valid issue at  all since IF doesn't change anything on pinging

**Comment by RatedRemoDemo** [comment] 2023-05-10 09:50
I've had a similar problem, although without the ImmediatelyFast mod. When opening the server list or scrolling down to load more servers on the list, the game freezes for up to nearly 10 seconds.

**Comment by x-yingcan-x** [comment] 2023-05-10 10:32
There is a same part that the game freezes when loading servers, but this mod doesn't change pinging. What else can cause this?inexplicable BUG :(
Maybe the title needs to be changed.

**Comment by FlorianMichael** [comment] 2023-05-10 11:05
Do you have auto detect enabled @RatedRemoDemo @x-yingcan-x ?

**Comment by x-yingcan-x** [comment] 2023-05-10 11:31
If I disable auto detect it will be a little better , "ImmediatelyFast", just to make it easier to notice

**Comment by RatedRemoDemo** [comment] 2023-05-11 00:36
> Do you have auto detect enabled @RatedRemoDemo @x-yingcan-x ?

No, it's disabled.
![image](https://github.com/FlorianMichael/ViaFabricPlus/assets/86170310/38097eb4-df52-4cf8-8cd2-4618c0b7f0b1)
![image](https://github.com/FlorianMichael/ViaFabricPlus/assets/86170310/e306a0e7-5efc-4701-a880-99dbc41e2bfa)
![image](https://github.com/FlorianMichael/ViaFabricPlus/assets/86170310/4694bd13-d3c4-43cd-8edc-c764a434c330)
Anything below these are off by default and I can't change them.

**Comment by FlorianMichael** [comment] 2023-05-22 18:05
I will close this since i can't really reproduce it or something else, I will take a look at it in the near future and re-open this issue

**Closed by FlorianMichael** 2023-05-22 18:05 UTC
Labels: bug

**Comment by x-yingcan-x** [comment] 2023-07-12 14:12
GOOD NEWS. This strange BUG strangly fixed during 2.7.8 -> 2.8.0 snapshot (at least on my client).
